version: "3"
services:
  app:
    build: .
    ports:
      - "8080:3000"
    command: npm run dev
    volumes:
      - .:/home/app/
      - /home/app/node_modules
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      NODE_ENV: dev
      DATABASE_URL: mysql://docker:docker@mysql:3306/docker
    networks:
      - network
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    networks:
      - network
networks:
  network:
    driver: bridge
